### ISSUE TITLE
Feel Free to Steal My CSS

### ISSUE THREAD

**Issue by killercup** [Hoverbear/acm-pandoc-paper#1]
I just read your article that linked to this repository. I've spend some time with Pandoc recently and wrote a few templates (for book-length stuff, though).

If you want to add some style(sheets), feel free to have a look [here](https://github.com/killercup/trpl-ebook/tree/master/lib) :)

**Comment by Hoverbear** [comment]
Is [this](http://killercup.github.io/trpl-ebook/trpl-2015-05-24.html) and example of it? I think I might have to!

**Comment by killercup** [comment]
Yep! Should be good to go with the default Pandoc template for HTML stuff.

**Comment by Hoverbear** [comment]
Included in 54ae739c74a1eadc5cdfb2e5cf2505949b9613b8, had to make a few modifications for preformatted code. :) Thanks!
